language: shell
os: linux
dist: xenial
git:
  depth: false

services:
  - docker

env:
  global:
    - LATEST=310
    - LATEST_LTS=39
  jobs:
    - "DB_TYPE=all DOCKERFILE=dockerfiles/apache/Dockerfile"
    - "DB_TYPE=mysqli DOCKERFILE=dockerfiles/apache/Dockerfile"
    - "DB_TYPE=pgsql DOCKERFILE=dockerfiles/apache/Dockerfile"
    - "DB_TYPE=all DOCKERFILE=dockerfiles/fpm_alpine/Dockerfile"
    - "DB_TYPE=mysqli DOCKERFILE=dockerfiles/fpm_alpine/Dockerfile"
    - "DB_TYPE=pgsql DOCKERFILE=dockerfiles/fpm_alpine/Dockerfile"

script: bash ./travis/build.sh

deploy:
  - provider: script
    on:
       branch: master
    script: bash ./travis/deploy.sh
       