language: shell
os: linux
dist: xenial
git:
  depth: false

branches:
  only:
    - master
    - dev

services:
  - docker

env:
  - VERSION=36
  - VERSION=37
  - VERSION=38
  - LATEST_LTS=36
  - LATEST=38
  - DB_TYPE=all
  - DB_TYPE=mysqli
  - DB_TYPE=pgsql
  - DOCKERFILE=dockerfiles/apache/Dockerfile
  - DOCKERFILE=dockerfiles/fpm_alpine/Dockerfile

script: bash travis/build.sh

deploy:
  - provider: script
    on:
       branch: master
    script: bash travis/~/co  deploy.sh
       