language: shell
os: linux
dist: xenial
git:
  depth: false

services:
  - docker

script: bash ./travis/gen_braches.sh

deploy:
  - provider: script
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.*$
    script: bash ./travis/deploy.sh
       