language: shell
os: linux
dist: xenial

services:
  - docker

script: bash ./travis/trigger_build.sh

deploy:
  - provider: script
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.*$
    script: bash ./travis/deploy.sh
       