language: shell
os: linux
dist: xenial
git:
  depth: false

branches:
  only:
    - master
    - dev

services:
  - docker

env:
  - DOCKER_COMPOSE_FILE=compose/lts/docker-compose-alpine-fpm.yml
  - DOCKER_COMPOSE_FILE=compose/lts/docker-compose-alpine-fpm.yml
  - DOCKER_COMPOSE_FILE=compose/latest/docker-compose-alpine-fpm.yml
  - DOCKER_COMPOSE_FILE=compose/latest/docker-compose-apache.yml

script: docker-compose -f $DOCKER_COMPOSE_FILE build

deploy:
  - provider: script
    on:
      branch: master
    script: |
        echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin &&\
        docker-compose \
          -f ./compose/latest/docker-compose-alpine-fpm.yml \
          -f ./compose/lts/docker-compose-apache.yml \
          -f ./compose/latest/docker-compose-apache.yml \
          -f ./compose/lts/docker-compose-alpine-fpm.yml \
        push