language: shell
os: linux
dist: xenial
git:
  depth: false

services:
  - docker

env:
  global:
    - LATEST=310
    - LATEST_LTS=39
  jobs:
    - "DB_TYPE=all DOCKERFILE=dockerfiles/apache/Dockerfile"
    - "DB_TYPE=mysqli DOCKERFILE=dockerfiles/apache/Dockerfile"
    - "DB_TYPE=pgsql  DOCKERFILE=dockerfiles/apache/Dockerfile"
    - "DB_TYPE=all DOCKERFILE=dockerfiles/fpm_alpine/Dockerfile"
    - "DB_TYPE=mysqli DOCKERFILE=dockerfiles/fpm_alpine/Dockerfile"
    - "DB_TYPE=pgsql DOCKERFILE=dockerfiles/fpm_alpine/Dockerfile"
   

jobs:
  include:
    - env:
        "VERSION=35"
      script: bash ./travis/build_docker.sh
    - env:
        "VERSION=36"
      script: bash ./travis/build_docker.sh
    - env:
        "VERSION=37"
      script: bash ./travis/build_docker.sh
    - env:
        "VERSION=38"
      script: bash ./travis/build_docker.sh
    - env:
        "VERSION=39"
      script: bash ./travis/build_docker.sh
    - env:
        "VERSION=310"
      script: bash ./travis/build_docker.sh

deploy:
  - provider: script
    on:
       branch: master
    script: bash ./travis/deploy.sh
       