version: "3.1"
services:
#database
  moodle_db_fpm_postgres:
    image: postgres:11-alpine
    volumes:
      - 'moodle_db_fpm_postgres_volume:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: $MOODLE_DB_NAME
      POSTGRES_USER: $MOODLE_DB_USER
      POSTGRES_PASSWORD: $MOODLE_DB_PASSWORD
  
  moodle_db_fpm_maria:
    image: mariadb:10.2
    volumes:
      - 'moodle_db_fpm_maria_volume:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: $MOODLE_DB_NAME
      MYSQL_USER: $MOODLE_DB_USER
      MYSQL_PASSWORD: $MOODLE_DB_PASSWORD
  
  moodle_db_fpm_mysql:
    image: mysql:5.7
    volumes:
      - 'moodle_db_fpm_mysql_volume:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: $MOODLE_DB_NAME
      MYSQL_USER: $MOODLE_DB_USER
      MYSQL_PASSWORD: $MOODLE_DB_PASSWORD

#nginx
  nginx:
    image: nginx:alpine
    ports:
      - 8970:8970
      - 8971:8971
      - 8972:8972
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "moodle_fpm_mysql_volume:/var/www/html/mysql"
      - "moodle_data_fpm_mysql_volume:/var/moodledata/mysql"
      - "moodle_fpm_mariadb_volume:/var/www/html/maria"
      - "moodle_data_fpm_mariadb_volume:/var/moodledata/maria"
      - "moodle_fpm_postgresql_volume:/var/www/html/postgresql"
      - "moodle_data_fpm_postgresql_volume:/var/moodledata/postgres"
    links:
      - moodle_fpm_mysql
      - moodle_fpm_maria
      - moodle_fpm_postgres

# moodle
  moodle_fpm_mysql:
    build:
      context: ../..
      dockerfile: ./dockerfiles/fpm/Dockerfile
      args:
        DB_TYPE: 'mysqli'
    image: ellakcy/moodle:mysql_fpm
    volumes:
      - "moodle_fpm_mysql_volume:/var/www/html"
      - "moodle_data_fpm_mysql_volume:/var/moodledata"
    environment:
      MOODLE_URL: http://0.0.0.0:8970
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_HOST: moodle_db_fpm_mysql
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: "false"
      MOODLE_SSL: "false"
  
  moodle_fpm_maria:
    build:
      context: ../..
      dockerfile: ./dockerfiles/fpm/Dockerfile
      args:
        DB_TYPE: 'mysqli'
    image: ellakcy/moodle:mysql_fpm
    volumes:
      - "moodle_fpm_mariadb_volume:/var/www/html"
      - "moodle_data_fpm_mariadb_volume:/var/moodledata"
    environment:
      MOODLE_URL: http://0.0.0.0:8971
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_HOST: moodle_db_fpm_maria
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: "false"
      MOODLE_SSL: "false"

  moodle_fpm_postgres:
    build:
      context: ../..
      dockerfile: ./dockerfiles/fpm/Dockerfile
      args:
        DB_TYPE: 'pgsql'
    image: ellakcy/moodle:postgresql_fpm
    volumes:
      - "moodle_fpm_postgresql_volume:/var/www/html"
      - "moodle_data_fpm_postgresql_volume:/var/moodledata"
    environment:
      MOODLE_URL: http://0.0.0.0:8972
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_HOST: moodle_db_fpm_postgres
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: "false"
      MOODLE_SSL: "false"


volumes:
  # Database volumes
  moodle_db_fpm_mysql_volume:
  moodle_db_fpm_maria_volume:
  moodle_db_fpm_postgres_volume:
  
  # Mysql volumes
  moodle_fpm_mysql_volume:
  moodle_data_fpm_mysql_volume:
 
  # Maria volumes
  moodle_fpm_mariadb_volume:
  moodle_data_fpm_mariadb_volume:  
 
  # postgres volumes
  moodle_fpm_postgresql_volume:
  moodle_data_fpm_postgresql_volume:
  