version: '3'
services:

#Alpine fpm based images
  #Basic alpine fpm image
  moodle_alpine_fpm_base:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_base
    image: ellakcy/moodle:alpine_fpm_base

  nginx:
   image: nginx:alpine
   ports:
     - "7870:7070"
   volumes:
     - './conf/nginx/nginx_mysql.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mysql'
     - 'moodle_alpine_fpm_mariadb'
     - 'moodle_alpine_fpm_psql'
   volumes_from:
     - 'moodle_alpine_fpm_mysql'
     - 'moodle_alpine_fpm_mariadb'
     - 'moodle_alpine_fpm_psql'
  
  #Mysql variant
  moodle_mysql_alpine_db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mysql:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_mysql
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mysql_alpine_db:moodle_db"
      - "moodle_alpine_fpm_base"
    volumes:
      - "./volumes/latest/php/mysql:/var/www/html"
    environment:
      MOODLE_DB_HOST: "moodle_mysql_alpine_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:7870"

  #Mariadb for demÎ¿nstration
  moodle_mariadb_alpine_db:
    image: mariadb:10.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mariadb:
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mariadb_alpine_db:moodle_db"
      - "moodle_alpine_fpm_base"
    environment:
      MOODLE_DB_HOST: "moodle_mariadb_alpine_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:7871"

  #Postgresql
   moodle_psql_alpine_db:
      image: postgres
      environment:
        POSTGRES_DB: "${MOODLE_DB_NAME}"
        POSTGRES_USER: '${MOODLE_MYSQL_USER}'
        POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_psql:
      build:
        context: .
        dockerfile: dockerfiles/fpm_alpine/Dockerfile_postgresql
      image: ellakcy/moodle:postgresql_fpm_alpine
      links:
        - "moodle_psql_alpine_db:moodle_db"
        - "moodle_alpine_fpm_base"
      environment:
        MOODLE_DB_HOST: "moodle_psql_alpine_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "http://0.0.0.0:7072"
