name: build_and_deploy

on:
  schedule:
    - cron: '23 0 * * 6' 
  push:
    branches: [
      master,
      dev
    ]

jobs:
  build_apache_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        moodle_version: [39,311,400]
        database: ['all','mysqli','pgsql']
    env:
      VERSION: ${{ matrix.moodle_version }}
      DB_TYPE: ${{ matrix.database }}
      LATEST: 401
      LATEST_LTS: 401
      DEFAULT_PHP: "7.4"
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        if: github.ref != 'refs/heads/dev'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Build Docker Images
        shell: bash
        run: |
          docker --version
          ls -l ./.github
          chmod +x ".github/build_docker.sh"
          .github/build_docker.sh 'dockerfiles/apache/Dockerfile'