name: build_and_deploy_80_php

on:
  schedule:
    - cron: '23 10 * * 6' 
  push:
    branches: [
      master,
      dev
    ]

jobs:
  build_apache_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        moodle_version: [311,400,401,402]
        database: ['all','mysqli','pgsql']
    env:
      VERSION: ${{ matrix.moodle_version }}
      DB_TYPE: ${{ matrix.database }}
      PHP_VERSION: "8.0"
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: github.ref != 'refs/heads/dev'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Build Docker Images
        shell: bash
        run: |
          docker --version
          ls -l ./.github
          chmod +x ".github/build_docker.sh"
          .github/build_docker.sh 'dockerfiles/apache/Dockerfile'

          
    